
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # Port API S3
      - "9001:9001"  # Port Console MinIO
    volumes:
      - "C:/pfe/minio:/data"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data --console-address ":9001"

  spark-master:
    build: 
      context: .
      dockerfile: Dockerfile-spark
    container_name: spark-master-1
    ports:
      - "8080:8080"  # UI Spark
      - "7077:7077"  # Port master
    environment:
      - SPARK_MODE=master
      - SPARK_HADOOP_FS_S3A_ENDPOINT=http://minio:9000
      - SPARK_HADOOP_FS_S3A_ACCESS_KEY=admin
      - SPARK_HADOOP_FS_S3A_SECRET_KEY=12345678

    volumes:
      - ./spark-jars:/opt/bitnami/spark/my-jars  
      - ./:/app/scripts
  

  spark-worker:
    build: 
      context: .
      dockerfile: Dockerfile-spark
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    deploy:
      replicas: 2  # 2 workers
    volumes:
      - ./spark-jars:/opt/bitnami/spark/my-jars

  qdrant:
      image: qdrant/qdrant
      container_name: pfe-qdrant
      ports:
        - "6333:6333"
      volumes:
        - "C:/pfe/qdrant:/qdrant/storage"